on: [push]

name: Build LPC

jobs:
  lpc_build:
    runs-on: ubuntu-latest
    name: Build LPC Code
    steps:
      - name: Build
        id: build
        uses: jlchmura/lpc-language-server/action@action-test
        with:
          lpc-config: ${{ github.workspace }}/efuns/ldmud/lpc-config.json
          
